export const FETCH_STOCK_DATA = 'FETCH_STOCK_DATA';
export const FETCH_STOCK_DATA_SUCCESS = 'FETCH_STOCK_DATA_SUCCESS';
export const FETCH_STOCK_DATA_ERROR = 'FETCH_STOCK_DATA_ERROR';

export const SUBMIT_EMAIL = 'SUBMIT_EMAIL';
export const SUBMIT_EMAIL_SUCCESS = 'SUBMIT_EMAIL_SUCCESS';
export const SUBMIT_EMAIL_ERROR = 'SUBMIT_EMAIL_ERROR';